services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      # Монтируем каталог из хоста в /app/data внутри контейнера
      - "${HOST_PATH:-./data}:/app/data:ro"
      - logs_volume:/app/logs:rw

volumes:
  logs_volume: